import sqlite3
conn=sqlite3.connect('lav.db')
print("OPENED")
cursor=conn.cursor()
cursor.execute("INSERT INTO names VALUES('lakshmi')")
cursor.execute("INSERT INTO names VALUES('lav')")
cursor.execute("INSERT INTO names VALUES('basketball')")
cursor.execute("INSERT INTO names VALUES('tennis')")
cursor.execute("INSERT INTO names VALUES('badminton')")
cursor.execute("INSERT INTO names VALUES('cricket')")
cursor.execute("INSERT INTO names VALUES('football')")
cursor.execute("INSERT INTO names VALUES('snookers')")
cursor.execute("INSERT INTO names VALUES('carroms')")
cursor.execute("INSERT INTO names VALUES('volleyball')")
cursor.execute("INSERT INTO names VALUES('swimming')")
cursor.execute("INSERT INTO names VALUES('throwball')")
cursor.execute("INSERT INTO names VALUES('baseball')")
cursor.execute("INSERT INTO names VALUES('dodgeball')")
cursor.execute("INSERT INTO names VALUES('golf')")
cursor.execute("INSERT INTO names VALUES('polo')")


conn.commit()
print("record")
#conn.execute("SELECT * FROM student1")
conn.close()
